### ISSUE TITLE
Make discover page links open in a new tab please

### ISSUE THREAD

**Issue by Paper-Folding** [kokororin/pixiv-ranking-new-tab#7]
Hey,could you please make every link in discover page opens in a new tab when left click the mouse?(which is to say target=_blank?)

**Comment by kokororin** [comment]
ok, I will add this feature

**Comment by Paper-Folding** [comment]
> ok, I will add this feature

Thank you,that would be nice of you!

**Comment by kokororin** [comment]
Option includes in 0.5.4. It will take almost 5 days to be approved by Google.
